name: Performance Testing with Apache Bench
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Apache Bench
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2-utils

      - name: Check Apache Bench version
        run: |
          ab -V

      - name: Performance Testing
        run: |
          ab -n 5 -c 3 http://peviitor.ro/
