name: Performance with ApacheBench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      t:
        description: 'run-time (sec)'
        required: true
        default: '900'
      c:
        description: 'Workload'
        required: true
        default: '3'
      url:
        description: 'Target URL for testing'
        required: true
        default: 'https://peviitor.ro/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Apache Bench
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2-utils

      - name: Check Apache Bench version
        run: |
          ab -V

      - name: Get current date and time
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Performance Testing
        id: perf_test
        run: |
          echo "Performance Test Results" > results.txt
          echo "=========================" >> results.txt
          echo "Test started at: ${{ env.DATE }}" >> results.txt
          echo "Run time (sec): ${{ github.event.inputs.t }}" >> results.txt
          echo "Workload (concurrency): ${{ github.event.inputs.c }}" >> results.txt
          echo "Target URL: ${{ github.event.inputs.url }}" >> results.txt
          echo "=========================" >> results.txt
          ab -t ${{ github.event.inputs.t }} -c ${{ github.event.inputs.c }} ${{ github.event.inputs.url }} >> results.txt 2>&1

      - name: Display Results
        run: |
          cat results.txt

      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: results.txt
