name: Performance Testing with Apache Bench
on:
  workflow_dispatch:
    inputs:
      t:
        description: 'Number of requests'
        required: true
        default: '5'
      c:
        description: 'Workload'
        required: true
        default: '3'
      url:
        description: 'Target URL for testing'
        required: true
        default: 'https://peviitor.ro/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Apache Bench
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2-utils

      - name: Check Apache Bench version
        run: |
          ab -V

      - name: Performance Testing
        id: perf_test
        run: |
          ab -t ${{ github.event.inputs.t }} -c ${{ github.event.inputs.c }} ${{ github.event.inputs.url }} > results.txt 2>&1

      - name: Display Results
        run: |
          cat results.txt

      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: results.txt
