name: Performance Testing with Apache Bench
on:
  workflow_dispatch:
    inputs:
      n:
        description: 'Number of requests'
        required: true
        default: '5'
      c:
        description: 'Workload'
        required: true
        default: '3'
      url:
        description: 'Target URL for testing'
        required: true
        default: 'http://peviitor.ro/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Apache Bench
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2-utils

      - name: Check Apache Bench version
        run: |
          ab -V

      - name: Performance Testing
        run: |
          ab -n ${{ github.event.inputs.n }} -c ${{ github.event.inputs.c }} ${{ github.event.inputs.url }}
